# Generated by Django 2.2 on 2020-01-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user',
            new_name='user_profile',
        ),
    ]
