# Generated by Django 2.2 on 2020-01-04 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_auto_20200104_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
